# Generated by Django 5.0.2 on 2024-03-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hallno',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
