# Generated by Django 5.0.2 on 2024-03-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_reservation_hallno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('stars', models.IntegerField(default=5)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='hallno',
            field=models.IntegerField(default=0),
        ),
    ]
