# Generated by Django 5.0.2 on 2024-03-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_reviews_alter_reservation_hallno'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='timeofvisit',
            field=models.IntegerField(default=0),
        ),
    ]
