# Generated by Django 5.0.2 on 2024-04-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_reviews_emailaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='timeofvisit',
        ),
        migrations.AddField(
            model_name='reservation',
            name='noofguests',
            field=models.CharField(default=50, max_length=100),
            preserve_default=False,
        ),
    ]
